/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ArquivoBinarioObra;
import controller.ArquivoBinarioPagamento;
import java.io.File;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.ListIterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Obra;
import model.Pagamento;

/**
 *
 * @author mathe
 */
public class CadastraPagamento extends javax.swing.JFrame {

    /**
     * Creates new form JanelaArquivoBinario
     */
    private File diretorioObra = null;
    private File diretorio = null;
    ArquivoBinarioPagamento arquivoBinario;
    ArrayList<Pagamento> listaPagamentos = new ArrayList<>();
    ArrayList<Pagamento> listaPagObra = new ArrayList<>();
    ArrayList<Obra> listaObras = null;
    Pagamento pag;
    Obra obra;
    int indice = 0;

    public CadastraPagamento() {
        initComponents();

        populaComboBoxObras();
    }

    public CadastraPagamento(File diretorio) {
        initComponents();

        this.diretorioObra = diretorio;
        populaComboBoxObras();

        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        labelPagamento(false, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerDia = new javax.swing.JSpinner();
        jSpinnerMes = new javax.swing.JSpinner();
        jSpinnerAno = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPagamento = new javax.swing.JLabel();
        jComboBoxObras = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldValorPag = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data:");

        jLabel7.setText("Valor:");

        jLabel8.setText("R$");

        jLabelPagamento.setText("Nenhum pagamento cadastrado");

        jComboBoxObras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxObrasItemStateChanged(evt);
            }
        });

        jLabel1.setText("Selecione a obra:");

        jTextFieldValorPag.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPagamento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldValorPag))))
                            .addComponent(jComboBoxObras, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jButtonAnterior)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonProximo)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabelPagamento)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldValorPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void populaComboBoxObras() {

        ArquivoBinarioObra arqObra = new ArquivoBinarioObra();
        if (diretorioObra == null) {
            JOptionPane.showMessageDialog(this, "Abra o arquivo obra!");
            diretorioObra = arqObra.abrirArquivo();
        }
        ObjectInputStream leitor = arqObra.CriaLeitorBinario(diretorioObra);
        if (leitor != null) {
            listaObras = arqObra.adcLista(leitor);
        }

        for (int ob = 0; ob < listaObras.size(); ob++) {
            jComboBoxObras.addItem(listaObras.get(ob).getNome());
        }

    }

    private void carregaListaPagamento() {
        arquivoBinario = new ArquivoBinarioPagamento();
        if (diretorio == null) {
            diretorio = arquivoBinario.abrirArquivo();

        }
        ObjectInputStream leitor = arquivoBinario.CriaLeitorBinario(diretorio);
        listaPagamentos = arquivoBinario.adcLista(leitor);

        if (!listaPagamentos.isEmpty()) {
            for (int j = 0; j < listaPagamentos.size(); j++) {
                if (listaPagamentos.get(j).getObra().getNome().equals(jComboBoxObras.getSelectedItem().toString())) { //contem a obra do combobox no arquivo de pagamento
                    listaPagObra.add(listaPagamentos.get(j)); //array com pagamento da obra selecionada
                }
            }
        }

        if (listaPagObra.isEmpty()) {
            labelPagamento(true, "Nenhum Pagamento Cadastrado!");
            jButtonNovo.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonAnterior.setEnabled(false);
            jButtonProximo.setEnabled(false);
        } else {
            jButtonNovo.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonAnterior.setEnabled(true);
            jButtonProximo.setEnabled(true);
        }
    }

    private void mostraPagamentos(Pagamento pag) {
        System.out.println(pag);
        if (pag != null) {
            jTextFieldValorPag.setText(pag.getValor());
            jSpinnerDia.setValue(pag.getDia());
            jSpinnerMes.setValue(pag.getMes());
            jSpinnerAno.setValue(pag.getAno());

        }
    }

    private Obra obraSelecionada() {
        for (int j = 0; j < listaObras.size(); j++) //pega a obra selecionada
        {
            if (jComboBoxObras.getItemAt(jComboBoxObras.getSelectedIndex()).equals(listaObras.get(j).getNome())) {
                return listaObras.get(j);
            }
        }

        return null;
    }

    private void labelPagamento(boolean show, String txt) {
        jLabelPagamento.setEnabled(show);
        jLabelPagamento.setText(txt);
    }

    private void limparCampos() {
        jTextFieldValorPag.setText("");
        jTextFieldValorPag.requestFocus();
        jSpinnerDia.setValue(1);
        jSpinnerMes.setValue(1);
        jSpinnerAno.setValue(2018);
    }

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        limparCampos();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (!listaPagObra.isEmpty()) {
            indice++;
        }

        arquivoBinario = new ArquivoBinarioPagamento();
        if (diretorio == null) {

            diretorio = arquivoBinario.abrirArquivo();

        } else {
            ObjectOutputStream escritor = arquivoBinario.CriaEscritorBinario(diretorio, false);

            pag = new Pagamento(jTextFieldValorPag.getText(), obraSelecionada(), (int) jSpinnerDia.getValue(),
                    (int) jSpinnerMes.getValue(), (int) jSpinnerAno.getValue());
            listaPagamentos.add(pag); //adiciona para salvar no arquivo  dps
            listaPagObra.add(pag);  //adiciona para mostrar os pagamentos

            arquivoBinario.EscreveObjeto(escritor, listaPagamentos, true);

        }

        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(true);

        JOptionPane.showMessageDialog(this, "O " + (indice + 1) + "º pagamento de " + listaPagObra.get(indice).getObra().getNome() + " foi adicionado com sucesso!");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        if (diretorio != null) {

            if (indice > 0) {
                indice--;
                mostraPagamentos(listaPagObra.get(indice));
                labelPagamento(true, (indice + 1) + "º Pagamento");

            } else if (indice == 0) {
                if (!listaPagObra.isEmpty()) {
                    mostraPagamentos(listaPagObra.get(0));
                    labelPagamento(true, (indice + 1) + "º Pagamento");
                }
                JOptionPane.showMessageDialog(this, "Fim da lista!");
            }

        } else {
            carregaListaPagamento();
            if (!listaPagObra.isEmpty()) {
                mostraPagamentos(listaPagObra.get(0));
                labelPagamento(true, (indice + 1) + "º Pagamento");
            }
        }

    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed

        if (diretorio != null) {

            if (indice < listaPagObra.size() - 1) {
                indice++;
                mostraPagamentos(listaPagObra.get(indice));
                labelPagamento(true, (indice + 1) + "º Pagamento");
            } else {
                JOptionPane.showMessageDialog(this, "Fim da lista!");
            }

        } else {
            carregaListaPagamento();
            if (!listaPagObra.isEmpty()) {
                mostraPagamentos(listaPagObra.get(0));
                jLabelPagamento.setEnabled(true);
                jLabelPagamento.setText((indice + 1) + "º Pagamento");
            }
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
/*        pag = new Obra(jTextFieldNome.getText(), jTextFieldFone.getText(), Integer.parseInt(jSpinnerTempoEstimado.getValue().toString()));
        
        arquivoBinario = new ArquivoBinarioPagamento();
          
        ObjectOutputStream escritor = arquivoBinario.CriaEscritorBinario(diretorio, false);

        pag = new Pagamento(jTextFieldValorPag.getText(), obraSelecionada(), (int) jSpinnerDia.getValue(),
                (int) jSpinnerMes.getValue(), (int) jSpinnerAno.getValue());
        
        listaPagamentos.set(indice, pag);
        listaPagamentos.add(pag); //adiciona para salvar no arquivo  dps
        listaPagObra.add(pag);  //adiciona para mostrar os pagamentos

        arquivoBinario.EscreveObjeto(escritor, listaPagamentos, true);
   
        JOptionPane.showMessageDialog(this, "Pagamento " + listaPagamentos.get(i).getNome() + " foi alterado com sucesso!");
*/
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        /*
        String pagamento = listaPagObra.get(indice).getValor();

        for (int i = 0; i < listaPagamentos.size(); i++) {
            if (listaPagObra.get(indice).equals(listaPagamentos.get(i))) {
                listaPagObra.remove(indice);
                listaPagamentos.remove(i);
            }
        }

        arquivoBinario = new ArquivoBinarioPagamento();
        ObjectOutputStream escritor = arquivoBinario.CriaEscritorBinario(diretorio, false);

        arquivoBinario.EscreveObjeto(escritor, listaPagamentos, true);

        limparCampos();

        JOptionPane.showMessageDialog(null, "O pagamento de R$" + pagamento + " foi excluido com sucesso!");

        if (listaPagObra.isEmpty()) {
            indice = 0;
            labelPagamento(true, "Nenhum Pagamento Cadastrado!");
            jButtonNovo.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonAnterior.setEnabled(false);
            jButtonProximo.setEnabled(false);
        }
        */
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboBoxObrasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxObrasItemStateChanged
        if (diretorio != null) {
            listaPagObra = new ArrayList<>();
            indice = 0;
            jTextFieldValorPag.setText("");
            jTextFieldValorPag.requestFocus();

            carregaListaPagamento();

            if (!listaPagObra.isEmpty()) {
                mostraPagamentos(listaPagObra.get(0));
                labelPagamento(true, (indice + 1) + "º Pagamento");
            }
        }
        System.out.println("Item " + jComboBoxObras.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxObrasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in jTextFieldValorPagailable, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxObras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPagamento;
    private javax.swing.JSpinner jSpinnerAno;
    private javax.swing.JSpinner jSpinnerDia;
    private javax.swing.JSpinner jSpinnerMes;
    private javax.swing.JFormattedTextField jTextFieldValorPag;
    // End of variables declaration//GEN-END:variables
}
